name: 2주마다 맛집 업데이트

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      # 💡 깃허브 액션 노드 24 경고를 해결하는 설정입니다.
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
      
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4
      
      - name: 파이썬 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: 필수 라이브러리 설치
        run: |
          pip install crewai langchain-openai python-dotenv requests supabase
        
      - name: 에이전트 가동
        run: python agent_test.py
        env:
          APP_LLM_KEY: "${{ secrets.OPENAI_API_KEY }}"
          NAVER_ID: "${{ secrets.NAVER_CLIENT_ID }}"
          NAVER_SECRET: "${{ secrets.NAVER_CLIENT_SECRET }}"
          DB_URL: "${{ secrets.SUPABASE_URL }}"
          DB_KEY: "${{ secrets.SUPABASE_KEY }}"
          CREWAI_TELEMETRY_OPT_OUT: "true"
          PYTHONUNBUFFERED: "1"